### ISSUE TITLE
missing mask

### ISSUE THREAD

**Issue by zhl8223** [3dv-casia/PanoVLM#2]
Hello, in your dataset Room and Floor I cann't find mask.jpg.  Could you please upload the mask.jpg? or how can I create mask image?

**Comment by DiantaoTu** [comment]
Sorry for the missing mask file in the dataset. We have uploaded a newer version with the mask included. Please check for the new download link.
Room: https://drive.google.com/file/d/1HOvOy4WI93J7dQxvZ8ErAX15Qbh5q0ps/view?usp=drive_link
Floor: https://drive.google.com/file/d/1UvyMLn_n2fGeiRPSqCttdGJYFajTxMYE/view?usp=drive_link
