### ISSUE TITLE
The point cloud is very sparse after coloring

### ISSUE THREAD

**Issue by Yellowshuohahaha** [3dv-casia/PanoVLM#3]
Why？ This is quite different from the number of point clouds originally collected in the dataset.
![image](https://github.com/3dv-casia/PanoVLM/assets/48409315/933be2ef-9800-400c-be28-1b23e1845bf1)

**Comment by DiantaoTu** [comment]
`ColorizeLidarMap` only processes lidar points with range `[near, far]`. And the final lidar cloud is fused every `k` cloud. 
By default, `near=1.5, far=35, k=5`.
You can change the settings in the code. Decreasing `k` to zero can fuse every lidar cloud but lead to a significantly large file size.
https://github.com/3dv-casia/PanoVLM/blob/84ae30e22db0b1d454693ba1a152fed350e2d23f/main.cpp#L545-L546

**Comment by Yellowshuohahaha** [comment]
> `ColorizeLidarMap` only processes lidar points with range `[near, far]`. And the final lidar cloud is fused every `k` cloud. By default, `near=1.5, far=35, k=5`. You can change the settings in the code. Decreasing `k` to zero can fuse every lidar cloud but lead to a significantly large file size.
> 
> https://github.com/3dv-casia/PanoVLM/blob/84ae30e22db0b1d454693ba1a152fed350e2d23f/main.cpp#L545-L546

That's work, thank you very much! The overall point cloud became much denser, but the color looked blurry in some places. Is there any test data for other scenarios? 
![image](https://github.com/3dv-casia/PanoVLM/assets/48409315/03daaea1-c0a7-40ad-9868-e09bf42960a3)

**Comment by DiantaoTu** [comment]
The blur is because of the misalignment between images and lidar clouds. The two sensors capture data with different viewing angles and some occlusion may occur, leading to wrong colorizing. This phenomenon is more obvious in indoor environment. We are currently compiling the dataset of outdoor scenes and it will be available as we finish.

**Comment by Yellowshuohahaha** [comment]
@DiantaoTu Thank you for your answer!

**Comment by Yellowshuohahaha** [comment]
> The blur is because of the misalignment between images and lidar clouds. The two sensors capture data with different viewing angles and some occlusion may occur, leading to wrong colorizing. This phenomenon is more obvious in indoor environment. We are currently compiling the dataset of outdoor scenes and it will be available as we finish.

Misalignment refers to the timestamp of the image and lidaris out of sync or their pose is not aligned?
