### ISSUE TITLE
Please list the extra parameters that need to be setting during compile opencv

### ISSUE THREAD

**Issue by Seekerzero** [3dv-casia/PanoVLM#4]
Hello,

Please list the extra parameters that need to be set during the compilation of opencv in the tutorial. seems like you use some extra library from opencv.

Thanks

**Comment by DiantaoTu** [comment]
In the old version of OpenCV (3.4.0 for example), the extra module should be installed, which includes the SIFT feature. The command is 
```
cd opencv-3.4.0/build
cmake -DOPENCV_EXTRA_MODULES_PATH="path_to_extra_modules/modules" ..
make -j
```
The extra module can be found [here](https://github.com/opencv/opencv_contrib).

In the newer version of OpenCV (3.4.11 and later), SIFT is removed from the extra module. Theoretically, you can just install OpenCV in normal way and run the code.

**Comment by Seekerzero** [comment]
But I do think the xfeature2d has remained inside the extra modules, as well as some CUDA libraries.

**Comment by DiantaoTu** [comment]
When I installed OpenCV, the command is 
```
cmake -D OPENCV_EXTRA_MODULES_PATH="path_to_extra_modules/modules" 
	 -DBUILD_opencv_cudacodec=OFF					
	 -D WITH_CUDA=ON
	 -D WITH_CUDNN=ON
	 -D OPENCV_DNN_CUDA=ON
	 -D ENABLE_FAST_MATH=1
	 -D CUDA_FAST_MATH=1
	 -D CUDA_ARCH_BIN=7.5
```
In fact, CUDA is only used in SIFT matching, and it is disabled by default.

**Comment by Seekerzero** [comment]
thanks, that should work
